api_platform:
    title: 'REBU (VTC) REST API'
    description: 'API Back end application pour REBU VTC'
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
